DROP DATABASE ltp IF EXISTS;
CREATE DATABASE ltp;

DROP TABLE projects IF EXISTS;
CREATE TABLE projects(
  id SERIAL NOT NULL,
  name VARCHAR NOT NULL,
  description VARCHAR,
  url VARCHAR NOT NULL,
  image_url VARCHAR,
  created DATE NOT NULL,
  updated DATE,
  cat_id SMALLINT
);

DROP TABLE categories IF EXISTS;
CREATE TABLE categories(
  id SERIAL NOT NULL,
  name VARCHAR NOT NULL
);